### ISSUE TITLE
Demoアプリケーションの追加

### ISSUE THREAD

**Issue by YuyaOka** [YuyaOka/Prog3_Shooting#7]
@joehamada @FUJIIYUYA 
今のDemoアプリケーション追加しました。
それぞれ何かあったらこのIssueにコメントしてください。

現状では、自分の環境(MacBook Pro)では、
<b>ゲームオーバー画面に遷移するまでに時間が掛かる</b>
というものが発生しています。

**Comment by YuyaOka** [comment]
2015/1/8
Demo更新
dc78ebd2d68d7433b21f89e1de48bab0f4e75d3a
上記コミットによって変更

**Comment by YuyaOka** [comment]
b199172ed3eaa59fb7cfe630838e52fd45633497
ゲーム作成終了によってデモ更新の必要がなくなる

**Comment by FUJIIYUYA** [comment]
１月の進歩報告書の他に　全体の活動報告書の作成を　1/28（水）までに完成させる。
（発表日の前半後半関係なしに）
